Translate 15.7
cwlin0416/freebsd-handbook pull request #1
Opened 2018-07-22 14:15 UTC by duidae

試翻15.7的一小段(如下)，再麻煩您看看是否ok

===============================
15.7. 在 MAC Jail 中使用 Nagios
This section demonstrates the steps that are needed to implement the Nagios network monitoring system in a MAC environment. This is meant as an example which still requires the administrator to test that the implemented policy meets the security requirements of the network before using in a production environment.

This example requires multilabel to be set on each file system. It also assumes that net-mgmt/nagios-plugins, net-mgmt/nagios, and www/apache22 are all installed, configured, and working correctly before attempting the integration into the MAC framework.

2018-07-22 16:57 UTC, cwlin0416 requested changes
Hi 請問您是使用什麼編輯程式編輯 PO 檔案的翻譯？，可能要設定 "超過 80 個字元要自動換行"。

因為您目前提交的版本已經把所有其他未翻譯的地方的格式也一併做修改了，這會導致未來在比對檔案差異上出現問題。

您在做 PR 前也可以查看一下 diff 確認您做的檔案變更只有針對您所翻譯的部份來避免這個問題發生。

2018-07-23 09:35 UTC, duidae commented
我是在ubuntu上用poedit, 翻譯完就按save, 我先設定"超過 80 個字元要自動換行"再試試看會不會又有把所有其他未翻譯的地方的格式也一併做修改的問題，謝謝！

2018-07-23 09:36 UTC, duidae commented
另想請問

# 產生翻譯結果 book.xml
make tran

# 將 book.xml 轉為 html
make FORMATS=html
make tran, make FORMATS=html這兩個我試了都出現error(make: ***No rule to make target 'tran'),  

我看repo上的makefile好像沒有'tran' 'FORMATS=html'這兩個target

想請問我要怎麼看我翻出來html的結果呢？

2018-07-24 13:46 UTC, cwlin0416 commented
要自己編譯說明文件必須在 FreeBSD 的環境上安裝相關的編譯套件，然後用 svn checkout 目前的文件原始檔並進入文件目錄後才能夠執行 make 的指令喔!

2018-07-29 13:51 UTC, closed without merging